NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"

ACCOUNTS=[
    "GCAD56MX3VL4YE3KIXPOWOMHTQYJOPYP7UQUQ2CAJQV4NYZ3566CAGKM",
    "GBFYOA4K4PLQJJV4LVLYFB3BBFUQGMJ3KIKMK32D4LFCPR2FEPRIGJYC",
]

[DOCUMENTATION]
ORG_NAME="Manangos"
ORG_URL="https://manangos.tk"
ORG_LOGO="http://manangos.tk/images/Logo.png"
ORG_DESCRIPTION="The fork of the fork of another fork."
ORG_TWITTER="@ManangosCoin"
ORG_OFFICIAL_EMAIL="manangoscoin@gmail.com"

[[CURRENCIES]]
code="Manangos"
issuer="GCAD56MX3VL4YE3KIXPOWOMHTQYJOPYP7UQUQ2CAJQV4NYZ3566CAGKM"
display_decimals=8
name="Manangos"
desc="The fork of the fork of another fork"
conditions="There will be only 420690000000 Manangos tokens in existence."
image="http://manangos.tk/images/Logo.png"
fixed_number=420690000000
